### ISSUE TITLE
Error parsing Python exception traceback with unclosed parentheses

### ISSUE THREAD

**Issue by salvisolamartinell** [googleapis/python-error-reporting#208] opened 2021-12-23 16:17 UTC
In Cloud Error Reporting, and in Cloud Logging as well, when a Python exception traceback ends with an unclosed parentheses, the traceback is not parsed properly from that point.

To reproduce with a simple Python snippet:
```
def f(*args):
    raise Exception()


def main():
    f(
        'multiline call to f',
        'this is a very common formatting',
    )


if __name__ == '__main__':
    main()
```
produces the following traceback:
```
Traceback (most recent call last):
  File "/home/salvi/.config/JetBrains/PyCharmCE2021.3/scratches/scratch.py", line 10, in <module>
    main()
  File "/home/salvi/.config/JetBrains/PyCharmCE2021.3/scratches/scratch.py", line 5, in main
    f(
  File "/home/salvi/.config/JetBrains/PyCharmCE2021.3/scratches/scratch.py", line 2, in f
    raise Exception()
Exception
```
which, seen from Cloud Error Reporting or Cloud Logging, stops being parsed properly at line `f(`.

**Comment by daniel-sanche** [comment] 2022-06-21 22:58
Hey @salvisolamartinell, sorry for the late response. I think I might need more information to resolve this. I just tested the code myself, and it looks like the traceback is properly captured on the Error Reporting dashboard, and in Cloud Logging for me:

![image](https://user-images.githubusercontent.com/3914119/174910110-a40b1c7b-7797-40a2-a0bf-c18fc4190303.png)

![image](https://user-images.githubusercontent.com/3914119/174910164-00b5c80a-b863-4649-abe0-b6b6192d30f6.png)

Let me know if you're expecting to see something different

**Comment by daniel-sanche** [comment] 2022-06-21 22:58
I'm going to close this for now, since it's been a while since it was reported and I can't reproduce the issue. Feel free to re-open if you're still having issues and I'll take another look at it

**Closed by daniel-sanche** 2022-06-21 22:58 UTC
Labels: api: clouderrorreporting, type: bug, priority: p2, :rotating_light:
